// Function to get unique country names from items

export const getUniqueValuesByKey = (key, items) => {
  const uniqueValues = new Set();
  const keysToExclude = ["fullName", "contact", "preferredName", "arrivalDate","contactInfo","email","lookingFor","leisureActivities","qualities"];
  items.forEach(item => {
    if (item[key] && !keysToExclude.includes(key)) {
      uniqueValues.add(item[key]);
    }
  });

  return Array.from(uniqueValues);
};

export const uniqueKeyNames = (key,item) => {
  const keys = new Set();
  const keysToExcludee = ["name", "contact", "preferredName", "arrivaldate","contactInfo"];
  items.forEach(item => {
    Object.keys(item).forEach(key => {
      if (!keysToExcludee.includes(key)) {
        keys.add(key);
      }
    });
  });

  return Object.keys(items[0]);
}

// function generateFilters(items) {
//     const keys = new Set();
//     items.forEach(item => {
//         Object.keys(item).forEach(key => keys.add(key));
//     });

//     return keys;
// }

// export const  getUniqueCountries = () => {
//   const uniqueCountries = new Set();
  
//   items.forEach(item => {
//     if (item.country) {
//       uniqueCountries.add(item.country);
//     }
//   });

//   return Array.from(uniqueCountries);
// };


// export const  getUniqueReligions = () => {
//   const uniqueReligion = new Set();
  
//   items.forEach(item => {
//     if (item.religion) {
//       uniqueReligion.add(item.religion);
//     }
//   });

//   return Array.from(uniqueReligion);
// };

export const items = [
  {
    "email": "mathiasdragosanchez@gmail.com",
    "arrivalDate": "8/6/2024",
    "religion": "N/A",
    "studyLevel": "business",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Gym/Exercise",
    "qualities": "Clean, Flexible",
    "fullName": "Mathias Drago Sanchez Muriel",
    "preferredName": "Mathias",
    "contactInfo": "Phone: 0034620939371",
    "country": "Spain",
    "apartmentPricing": "N/A"
  },
  {
    "email": "jimiahfilterman02@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "N/A",
    "studyLevel": "Senior in Business Administration ",
    "apartmentLocation": "Westgates Apartments",
    "lookingFor": "Someone to sublease and take my room",
    "familyStatus": "One female roommate in other room.",
    "roommatePreference": "A biological Female",
    "transportation": "Close to campus, bus or walk",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Jimiah Filterman",
    "preferredName": "Jimiah",
    "contactInfo": "Phone: 6012998876",
    "country": "Bahamas",
    "apartmentPricing": "N/A"
  },
  {
    "email": "asmakhadiza884@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "Islam",
    "studyLevel": "Doctoral ",
    "apartmentLocation": "117 N 36 Avenue ",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Married - living with spouse",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Friendly",
    "fullName": "Khadiza Akter",
    "preferredName": "Asma",
    "contactInfo": "Phone: 6019130996",
    "country": "Bangladesh",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "amatunnoor902@gmail.com",
    "arrivalDate": "8/10/2024",
    "religion": "Islam",
    "studyLevel": "Master in Public Health ",
    "apartmentLocation": "N/A",
    "lookingFor": "a place in a shared bedroom., someone to share my bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Listening to Music",
    "qualities": "Clean, Caring, Good Cook",
    "fullName": "Amatun Noor Prapty",
    "preferredName": "Amatun",
    "contactInfo": "No valid contact info",
    "country": "Bangladesh",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "itstan01@gmail.com",
    "arrivalDate": "7/25/2024",
    "religion": "Islam",
    "studyLevel": "Freshmen in Computer Science ",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I have a bicycle.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Understanding",
    "fullName": "Kamrul Islam",
    "preferredName": "Tan.",
    "contactInfo": "Phone: 8801990181968, WhatsApp: 8801990181968, Facebook: https://www.facebook.com/profile.php?id=100077337917258&mibextid=ZbWKwL",
    "country": "Bangladesh",
    "apartmentPricing": "N/A"
  },
  {
    "email": "shadmanshakib.psy@gmail.com",
    "arrivalDate": "8/2/2024",
    "religion": "Islam",
    "studyLevel": "PhD in Psychology ",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom., someone to rent the other bedroom in my apt., someone to share my bedroom.",
    "familyStatus": "Married - but family not coming.",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "No Pork",
    "leisureActivities": "Reading",
    "qualities": "Clean, Friendly",
    "fullName": "Shadman Shakib.",
    "preferredName": "Shadman",
    "contactInfo": "Phone: 01610027434",
    "country": "Bangladesh",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "kms.andalib@gmail.com",
    "arrivalDate": "8/6/2024",
    "religion": "Islam",
    "studyLevel": "PhD in Biological Science",
    "apartmentLocation": "N/A",
    "lookingFor": "Single Room",
    "familyStatus": "Married - but family not coming.",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "K M Salim Andalib",
    "preferredName": "Salim",
    "contactInfo": "Facebook: https://www.facebook.com/andalibopu",
    "country": "Bangladesh",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "buobaidullah@gmail.com",
    "arrivalDate": "8/12/2024",
    "religion": "Islam",
    "studyLevel": "MA in Political Science ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Reading",
    "qualities": "N/A",
    "fullName": "Md. Obaidullah",
    "preferredName": "Muhammad",
    "contactInfo": "Phone: 01726261746",
    "country": "Bangladesh",
    "apartmentPricing": "N/A"
  },
  {
    "email": "shefabmb17@gmail.com",
    "arrivalDate": "8/10/2024",
    "religion": "Islam",
    "studyLevel": "Phd in Communication ",
    "apartmentLocation": "N/A",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Married - living with spouse",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Shefa Tabassum",
    "preferredName": "Shefa",
    "contactInfo": "Phone: 1521105054",
    "country": "Bangladesh",
    "apartmentPricing": "N/A"
  },
  {
    "email": "asmita.rahman2013@gmail.com",
    "arrivalDate": "7/28/2024",
    "religion": "N/A",
    "studyLevel": "Biomedical Sciences, second year",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A woman",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Clean, Friendly, Hygienic",
    "fullName": "Asmita Rahman",
    "preferredName": "Asmita",
    "contactInfo": "Phone: 8801706271478",
    "country": "Bangladesh",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "violinovitor@outlook.com",
    "arrivalDate": "08/02/2024",
    "religion": "N/A",
    "studyLevel": "Masters Degree in Music Performance Violin ",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Respectful",
    "fullName": "Jo\u00e3o Vitor Gonzaga",
    "preferredName": "Jo\u00e3o",
    "contactInfo": "Phone: 5511949110263, WhatsApp: 5511949110263",
    "country": "Brazil",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "palomavieiraviolin@gmail.com",
    "arrivalDate": "7/30/2024",
    "religion": "Christianity",
    "studyLevel": "Masters in Music ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "Lactose Intolerance",
    "leisureActivities": "N/A",
    "qualities": "Understanding",
    "fullName": "Paloma Izadora Aparecida Moreira Vieira",
    "preferredName": "Paloma",
    "contactInfo": "Phone: 5531984848886",
    "country": "Brazil",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "johanna.tarcson@gmx.de",
    "arrivalDate": "08/12/2024",
    "religion": "N/A",
    "studyLevel": "DMA music",
    "apartmentLocation": "Windridge apartments",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Johanna Tarcson",
    "preferredName": "Johanna",
    "contactInfo": "No valid contact info",
    "country": "Germany",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "hassanissaka402@gmail.com",
    "arrivalDate": "8/23/2002",
    "religion": "N/A",
    "studyLevel": "Undergraduate",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Issaka Hassan Tia",
    "preferredName": "Issaka",
    "contactInfo": "Phone: 233593415889",
    "country": "Ghana",
    "apartmentPricing": "N/A"
  },
  {
    "email": "richardboglo7@gmail.com",
    "arrivalDate": "8/12/2024",
    "religion": "Christianity",
    "studyLevel": "Masters in Economic Development ",
    "apartmentLocation": "Westgate and Eagle flatts",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Supportive",
    "fullName": "Richard kofi Boglo",
    "preferredName": "Richard",
    "contactInfo": "Phone: 0240031807",
    "country": "Ghana",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "anokyerockson83@gmail.com",
    "arrivalDate": "8/16/2024",
    "religion": "Christianity",
    "studyLevel": "PhD Biological Sciences ",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Clean",
    "fullName": "Rockson Anokye (",
    "preferredName": "Rockson",
    "contactInfo": "Phone: 233241727035, WhatsApp: 233241727035",
    "country": "Ghana",
    "apartmentPricing": "N/A"
  },
  {
    "email": "Jeremiah.Williams@usm.edu",
    "arrivalDate": "8/31/2024",
    "religion": "Christianity",
    "studyLevel": "Masters in Music Education",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I have a bicycle.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Clean, Respectful",
    "fullName": "Jeremiah Williams",
    "preferredName": "Jeremiah",
    "contactInfo": "Phone: 9295697195",
    "country": "Guyana",
    "apartmentPricing": "$900+/mo"
  },
  {
    "email": "mishraabhishek.2021@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "Hinduism",
    "studyLevel": "Masters - computer science ",
    "apartmentLocation": "Blainewood Oaks Apartment ",
    "lookingFor": "Share Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I have a car.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Gym/Exercise",
    "qualities": "Clean, Friendly",
    "fullName": "Abhishek Mishra",
    "preferredName": "Abhishek",
    "contactInfo": "Phone: 6018180658",
    "country": "India",
    "apartmentPricing": "N/A"
  },
  {
    "email": "mounica.kusuma@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "Christianity",
    "studyLevel": "MPH",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Mounica Kusuma",
    "preferredName": "Mounica",
    "contactInfo": "Mounica Kusuma (Facebook)",
    "country": "India",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "salmk19112@gmail.com",
    "arrivalDate": "7/24/2024",
    "religion": "Islam",
    "studyLevel": "MPH",
    "apartmentLocation": "N/A",
    "lookingFor": "Bath Attached Bedroom",
    "familyStatus": "Married (Girl child of 5.5yrs will join me- NO SPOUSE)",
    "roommatePreference": "a biological female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "Halal",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Friendly, Understanding",
    "fullName": "Salwa Mohamed",
    "preferredName": "Salwa",
    "contactInfo": "Phone: 918590507151",
    "country": "India",
    "apartmentPricing": "N/A"
  },
  {
    "email": "badabossnew@gmail.com",
    "arrivalDate": "7/26/2024",
    "religion": "Islam",
    "studyLevel": "Masters in Public Health",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Me & my 6 year old girl",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Salwa Mohamed Musarikandy",
    "preferredName": "Salwa",
    "contactInfo": "Facebook: https://www.facebook.com/Basil.mk/",
    "country": "India",
    "apartmentPricing": "N/A"
  },
  {
    "email": "jonathannavara16@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "Christianity",
    "studyLevel": "Masters in Public Health",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Jonathan Navara",
    "preferredName": "Jonathan",
    "contactInfo": "No valid contact info",
    "country": "India",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "lalithakrishna65@gmail.com",
    "arrivalDate": "7/25/2024",
    "religion": "N/A",
    "studyLevel": "Computer science ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Couple - 2 people living together",
    "roommatePreference": "A biological Female",
    "transportation": null,
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Lalitha Inturi",
    "preferredName": "Lalitha",
    "contactInfo": "Phone: 7693781483",
    "country": "Indian",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "dbigalieva01@gmail.com",
    "arrivalDate": "8/12/2024",
    "religion": "N/A",
    "studyLevel": "Masters in counseling psychology ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Couple - doing long distance",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Reading",
    "qualities": "Clean, Organized, Respectful, Good Listener",
    "fullName": "Jamilya",
    "preferredName": "Jamilya",
    "contactInfo": "Phone: 34615223569, WhatsApp: 34615223569",
    "country": "Kazakhstan",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "sandhyathapa1427@gmail.com",
    "arrivalDate": "8/10/2024",
    "religion": "Hinduism",
    "studyLevel": "Freshman in forensic sciences ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "No Beef",
    "leisureActivities": "Crocheting",
    "qualities": "N/A",
    "fullName": "Sandhya Thapa",
    "preferredName": "Sandhya",
    "contactInfo": "Facebook: https://www.facebook.com/share/j9W7tP2SMJvkjA6Q/?mibextid=qi2Omg",
    "country": "Nepal",
    "apartmentPricing": "N/A"
  },
  {
    "email": "rhishguragain@gmail.com",
    "arrivalDate": "8/28/2024",
    "religion": "Hinduism",
    "studyLevel": "BSc in Computer Science",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Clean, Respectful, Understanding",
    "fullName": "Rhishika Guragain",
    "preferredName": "Rhishika",
    "contactInfo": "No valid contact info",
    "country": "Nepal",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "pratima.rajbanshi@usm.edu",
    "arrivalDate": "8/1/2024",
    "religion": "N/A",
    "studyLevel": "UG Computer Science",
    "apartmentLocation": "Blainewood Oaks",
    "lookingFor": "Share Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I have a bicycle.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Relaxing",
    "qualities": "N/A",
    "fullName": "Pratima Rajbanshi",
    "preferredName": "Zenith",
    "contactInfo": "Zenith Chetri (Facebook)",
    "country": "Nepal",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "prasannarijal@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "N/A",
    "studyLevel": "Sophomore in Computer Engineering",
    "apartmentLocation": "Blainewoods Apartment",
    "lookingFor": "Share Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "Vegetarian",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Transparent Communication, Clear Communication",
    "fullName": "Prasanna Rijal",
    "preferredName": "Prasanna",
    "contactInfo": "Phone: 6016581524",
    "country": "Nepal",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "bibekganesh983@gmail.com",
    "arrivalDate": "8/12/2024",
    "religion": "Hinduism",
    "studyLevel": "Undergraduate in Computer Science ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Bibek Ganesh",
    "preferredName": "Bibek",
    "contactInfo": "Phone: 9804949594",
    "country": "Nepal",
    "apartmentPricing": "$900+/mo"
  },
  {
    "email": "tamangniyati18@gmail.com",
    "arrivalDate": "8/12/2024",
    "religion": "N/A",
    "studyLevel": "Freshmen in Microbiology",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "Gluten Free",
    "leisureActivities": "Cooking/Exploring Cafes",
    "qualities": "Friendly, Quiet",
    "fullName": "Niyati Tamang",
    "preferredName": "Niyati",
    "contactInfo": "Phone: 9779840726784",
    "country": "Nepal",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "sabeinartha@gmail.com",
    "arrivalDate": "7/23/2024",
    "religion": "Hinduism",
    "studyLevel": "PhD in biology",
    "apartmentLocation": "N/A",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Sabin Shrestha",
    "preferredName": "Sabin",
    "contactInfo": "Phone: 9779860033148",
    "country": "Nepal",
    "apartmentPricing": "$900+/mo"
  },
  {
    "email": "nhoojahm@gmail.com",
    "arrivalDate": "8/3/2024",
    "religion": "N/A",
    "studyLevel": "Freshman in Computer Science",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom., someone to rent the other bedroom in my apt., someone to share my bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Clean, Organized, Respectful, Friendly, Easygoing, Flexible",
    "fullName": "Nhoojah Maharjan",
    "preferredName": "Nhoojah",
    "contactInfo": "No valid contact info",
    "country": "Nepal",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "abhatta30@gmail.com",
    "arrivalDate": "8/4/2024",
    "religion": "Hinduism",
    "studyLevel": "Masters in Physics",
    "apartmentLocation": "N/A",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Patient",
    "fullName": "Aakash Bhatta",
    "preferredName": "Aakash",
    "contactInfo": "Phone: 9779848429607",
    "country": "Nepal",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "abhinay.shrestha11@gmail.com",
    "arrivalDate": "7/25/2024",
    "religion": "Hinduism",
    "studyLevel": "Masters in Computer and Information Science",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Reading",
    "qualities": "N/A",
    "fullName": "Abhinay Shrestha",
    "preferredName": "Abhinay",
    "contactInfo": "Phone: 9779840219384",
    "country": "Nepal",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "w10186965@usm.edu",
    "arrivalDate": "8/1/2024",
    "religion": "Buddhism",
    "studyLevel": "MBA",
    "apartmentLocation": "Windridge Apartments",
    "lookingFor": "a private bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Gym/Exercise",
    "qualities": "Clean, Flexible, Hygienic",
    "fullName": "Sonam Gurung",
    "preferredName": "Sonam",
    "contactInfo": "Facebook: https://www.facebook.com/sonamchoedon103/",
    "country": "Nepal",
    "apartmentPricing": "N/A"
  },
  {
    "email": "leongiri348@gmail.com",
    "arrivalDate": "7/25/2024",
    "religion": "Hinduism",
    "studyLevel": "Freshman in computer science ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Understanding",
    "fullName": "Leon Giri",
    "preferredName": "Leon",
    "contactInfo": "Phone: 9779842054748",
    "country": "Nepal",
    "apartmentPricing": "N/A"
  },
  {
    "email": "subodhbhattarai477@gmail.com",
    "arrivalDate": "8/11/2024",
    "religion": "Hinduism",
    "studyLevel": "Freshman in Computer Engineering",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Social, Fun",
    "fullName": "Subodh Bhattarai",
    "preferredName": "Subodh",
    "contactInfo": "Facebook: https://www.facebook.com/subodh.bhattarai.477",
    "country": "Nepal",
    "apartmentPricing": "N/A"
  },
  {
    "email": "prashantbaral0269@gmail.com",
    "arrivalDate": "8/5/2024",
    "religion": "Hinduism",
    "studyLevel": "Bachelors in Computer Science",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Friendly, Negotiable",
    "fullName": "Prasant Baral",
    "preferredName": "Prasant",
    "contactInfo": "Phone: 9779802425820",
    "country": "Nepal",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "tarbi.pyakurel@usm.edu",
    "arrivalDate": "8/1/2024",
    "religion": "N/A",
    "studyLevel": "Freshman in Computer Science",
    "apartmentLocation": "N/A",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Couple - 2 people living together",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Tarbi Pyakurel",
    "preferredName": "Tarbi",
    "contactInfo": "Phone: 6013079272",
    "country": "Nepali",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "rubinaguragain@gmail.com",
    "arrivalDate": "8/19/2024",
    "religion": "N/A",
    "studyLevel": "Junior in Computer Science ",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Rubina Guragain",
    "preferredName": "Rubina",
    "contactInfo": "Phone: 4699686139",
    "country": "Nepali",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "Tolaxvalentine@gmail.com",
    "arrivalDate": "8/3/2024",
    "religion": "Christianity",
    "studyLevel": "Ph.D Biological sciences ",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Married - spouse and child/children coming this year",
    "roommatePreference": "A biological Male",
    "transportation": null,
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Gym/Exercise",
    "qualities": "Caring",
    "fullName": "Tolulope Ademulegun",
    "preferredName": "Tolu",
    "contactInfo": "Phone: 2347030805149",
    "country": "Nigeria",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "veritynwabuisi@gmail.com",
    "arrivalDate": "7/1/2024",
    "religion": "Christianity",
    "studyLevel": "Freshman Mathematics Major",
    "apartmentLocation": "N/A",
    "lookingFor": "a place in a shared bedroom., off campus housing",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Clean, Organized",
    "fullName": "Verity Nwabuisi",
    "preferredName": "Verity",
    "contactInfo": "Phone: 16019131806",
    "country": "Nigeria",
    "apartmentPricing": "N/A"
  },
  {
    "email": "chinenye.edomobi73@gmail.com",
    "arrivalDate": "8/10/2024",
    "religion": "Christianity",
    "studyLevel": "Bachelors in Nursing- Sophomore",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Chinenye Edomobi",
    "preferredName": "Chinenye",
    "contactInfo": "Phone: 9252045873",
    "country": "Nigeria",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "ulunnaugoh@gmail.com",
    "arrivalDate": "8/7/2024",
    "religion": "Christianity",
    "studyLevel": "Masters in Public Health ",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Married - but family not coming.",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Caring, Easygoing, Diligent",
    "fullName": "Ulunna Rita Ugoh",
    "preferredName": "Rita",
    "contactInfo": "Phone: 2348127744849",
    "country": "Nigeria",
    "apartmentPricing": "N/A"
  },
  {
    "email": "oduweugo@gmail.com",
    "arrivalDate": "8/6/2024",
    "religion": "Christianity",
    "studyLevel": "PhD Biological Sciences ",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Playing Games",
    "qualities": "Clean, Good Cook",
    "fullName": "Ugochukwu Kenneth Oduwe",
    "preferredName": "Ugochukwu",
    "contactInfo": "Phone: 2349156495006",
    "country": "Nigeria",
    "apartmentPricing": "$900+/mo"
  },
  {
    "email": "ayeshamaheen042@gmail.com",
    "arrivalDate": "8/4/2024",
    "religion": "Islam",
    "studyLevel": "MBA",
    "apartmentLocation": "3318 Pearl St Apt J, Hattiesburg, MS, 39401",
    "lookingFor": "Share Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "No Alcohol",
    "leisureActivities": "Watching Movies/TV",
    "qualities": "Friendly",
    "fullName": "Ayesha Maheen",
    "preferredName": "Ayesha",
    "contactInfo": "Phone: 03310241223",
    "country": "Pakistan",
    "apartmentPricing": "N/A"
  },
  {
    "email": "malikhasaanahmad@gmail.com",
    "arrivalDate": "8/1/2024",
    "religion": "Islam",
    "studyLevel": "Sophomore in Computer Science",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "No Pork",
    "leisureActivities": "Socializing/Parties",
    "qualities": "Clean, Respectful, Caring, Flexible",
    "fullName": "Malik",
    "preferredName": "Malik",
    "contactInfo": "Phone: 6692494596",
    "country": "Pakistan",
    "apartmentPricing": "$900+/mo"
  },
  {
    "email": "nolubabaloruth@gmail.com",
    "arrivalDate": "1/8/2024",
    "religion": "Christianity",
    "studyLevel": "Masters in Sport Management & Sport Security ",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Respectful, Friendly, Understanding",
    "fullName": "Nolubabalo Sishuba",
    "preferredName": "Luba",
    "contactInfo": "Luba Ruth Sishuba (Facebook)",
    "country": "South africa",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "babatundeadebayo121@gmail.com",
    "arrivalDate": "7/29/2024",
    "religion": "Islam",
    "studyLevel": "PhD HCD",
    "apartmentLocation": "N/A",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "I have a car.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Listening to Music",
    "qualities": "Clean, Clean, Clear Communication, Supportive",
    "fullName": "Babatunde Adebayo",
    "preferredName": "Babatunde",
    "contactInfo": "Phone: 447427171272",
    "country": "United Kingdom",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "tohurakhanam49@gmail.com",
    "arrivalDate": "8/15/2024",
    "religion": "Islam",
    "studyLevel": "Junior in Biomedical Science ",
    "apartmentLocation": "N/A",
    "lookingFor": "a private bedroom., a place in a shared bedroom.",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "Clean, Quiet",
    "fullName": "Tohura Khanam Easha Tohura",
    "preferredName": "Tohura",
    "contactInfo": "Phone: 6013079716",
    "country": "Bangladesh",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "sandesh.bhattarai@usm.edu",
    "arrivalDate": "8/15/2024",
    "religion": "Hinduism",
    "studyLevel": "Sophomore in Computer Science",
    "apartmentLocation": "N/A",
    "lookingFor": "Shared Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "It doesn't matter to me.",
    "transportation": "Planning to get a car after I arrive there",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Sandesh Bhattarai",
    "preferredName": "Sandesh",
    "contactInfo": "Phone: 6012998937",
    "country": "Nepal",
    "apartmentPricing": "$700+/mo"
  },
  {
    "email": "osobukolakanmi@gmail.com",
    "arrivalDate": "8/13/2024",
    "religion": "Christianity",
    "studyLevel": "Sophomore in biology ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "Drawing",
    "qualities": "Clean, Tolerant",
    "fullName": "Ayokanmi Osobukola",
    "preferredName": "Ayokanmi",
    "contactInfo": "Phone: 6019138488, WhatsApp: 2349073163885",
    "country": "Nigeria",
    "apartmentPricing": "$800+/mo"
  },
  {
    "email": "aryalsuwan.2003@gmail.com",
    "arrivalDate": "8/7/2024",
    "religion": "N/A",
    "studyLevel": "Sophomore CS",
    "apartmentLocation": "Westgate Apartments",
    "lookingFor": "Rent Other Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Suwan Aryal",
    "preferredName": "Suwan",
    "contactInfo": "Phone: 7734833993",
    "country": "Nepal",
    "apartmentPricing": "N/A"
  },
  {
    "email": "rabiu.m@unilorin.edu.ng",
    "arrivalDate": "8/14/2024",
    "religion": "Islam",
    "studyLevel": "PhD in Biological science ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Married - but family not coming.",
    "roommatePreference": "A biological Male",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "No Pork",
    "leisureActivities": "Football",
    "qualities": "N/A",
    "fullName": "Rabiu Musa",
    "preferredName": "Musa",
    "contactInfo": "Phone: 2348061363033",
    "country": "Nigeria",
    "apartmentPricing": "N/A"
  },
  {
    "email": "rabeeafatima65@gmail.com",
    "arrivalDate": "8/20/2024",
    "religion": "N/A",
    "studyLevel": "Bsc computer engineering ",
    "apartmentLocation": "N/A",
    "lookingFor": "Private Bedroom",
    "familyStatus": "Single",
    "roommatePreference": "A biological Female",
    "transportation": "I don't have any transportation, so I need to live near campus.",
    "dietaryRestrictions": "N/A",
    "leisureActivities": "N/A",
    "qualities": "N/A",
    "fullName": "Rabeea Fatima",
    "preferredName": "Rabeea",
    "contactInfo": "Phone: 6019138759",
    "country": "Pakistan",
    "apartmentPricing": "$800+/mo"
  }
]

